import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, useAuth } from './contexts/AuthContext';
import { CityProvider } from './contexts/CityContext';
import { ConfirmProvider } from './hooks/useConfirm';
import { ErrorBoundary } from './components/ErrorBoundary';

// Layouts
import AppLayout from './layouts/AppLayout';

// Pages
import HomePage from './pages/HomePage';
import OnboardingPage from './pages/OnboardingPage';
import AuthPage from './pages/AuthPage';
import MerchantPage from './pages/MerchantPage';
import ProfilePage from './pages/ProfilePage';
import AdminDashboard from './pages/AdminDashboard';
import MerchantDashboard from './pages/MerchantDashboard';
import DriverDashboard from './pages/DriverDashboard';
import ProviderDashboard from './pages/ProviderDashboard';
import FeedbackPage from './pages/FeedbackPage';
import BusSchedulePage from './pages/BusSchedulePage';
import ProductPage from './pages/ProductPage';
import JobsPage from './pages/JobsPage';
import SearchPage from './pages/SearchPage';
import FavoritesPage from './pages/FavoritesPage';
import CreatePage from './pages/CreatePage';
import CampaignsPage from './pages/CampaignsPage';
import CampaignDetailPage from './pages/CampaignDetailPage';
import BannerPage from './pages/BannerPage';

import ComerciosPage from './pages/ComerciosPage';
import ServicosPage from './pages/ServicosPage';
import ProviderPage from './pages/ProviderPage';
import GarbageCollectionPage from './pages/GarbageCollectionPage';
import AdoptionPage from './pages/AdoptionPage';
import DynamicPage from './pages/DynamicPage';
import MotoristasPage from './pages/MotoristasPage';

function ProtectedRoute({ children }: { children: React.ReactNode }) {
  const { currentUser, userProfile, loading } = useAuth();
  
  if (loading) return <div className="h-screen w-full flex items-center justify-center bg-bg-base"><div className="animate-spin w-8 h-8 border-4 border-primary border-t-transparent rounded-full"></div></div>;
  if (!currentUser) return <Navigate to="/login" replace />;
  if (!userProfile && window.location.pathname !== '/onboarding') return <Navigate to="/onboarding" replace />;
  
  return <>{children}</>;
}

export default function App() {
  return (
    <ErrorBoundary>
      <BrowserRouter>
        <CityProvider>
          <AuthProvider>
          <ConfirmProvider>
            <Routes>
              <Route path="/login" element={<AuthPage />} />
              <Route path="/onboarding" element={<ProtectedRoute><OnboardingPage /></ProtectedRoute>} />
              
              <Route element={<AppLayout />}>
                <Route path="/" element={<HomePage />} />
                <Route path="/cidade/:slug" element={<HomePage />} />
                <Route path="/comercios" element={<ComerciosPage />} />
              <Route path="/servicos" element={<ServicosPage />} />
              <Route path="/motoristas" element={<MotoristasPage />} />
              <Route path="/comercio/:id" element={<MerchantPage />} />
              <Route path="/prestador/:id" element={<ProviderPage />} />
              <Route path="/produto/:id" element={<ProductPage />} />
              <Route path="/onibus" element={<BusSchedulePage />} />
              <Route path="/coleta" element={<GarbageCollectionPage />} />
              <Route path="/adocao" element={<AdoptionPage />} />
              <Route path="/busca" element={<SearchPage />} />
              <Route path="/empregos" element={<JobsPage />} />
              <Route path="/campanhas" element={<CampaignsPage />} />
              <Route path="/campanha/:id" element={<CampaignDetailPage />} />
              <Route path="/banner/:id" element={<BannerPage />} />
              
              {/* Dynamic Pages generated by AI */}
              <Route path="/p/*" element={<DynamicPage />} />
              
              {/* Protected features */}
              <Route path="/favoritos" element={<ProtectedRoute><FavoritesPage /></ProtectedRoute>} />
              <Route path="/criar" element={<ProtectedRoute><CreatePage /></ProtectedRoute>} />
              <Route path="/perfil" element={<ProtectedRoute><ProfilePage /></ProtectedRoute>} />
            </Route>

            <Route path="/feedback" element={<ProtectedRoute><FeedbackPage /></ProtectedRoute>} />
            <Route path="/admin" element={<ProtectedRoute><AdminDashboard /></ProtectedRoute>} />
            <Route path="/comerciante/painel" element={<ProtectedRoute><MerchantDashboard /></ProtectedRoute>} />
            <Route path="/motorista/painel" element={<ProtectedRoute><DriverDashboard /></ProtectedRoute>} />
            <Route path="/prestador/painel" element={<ProtectedRoute><ProviderDashboard /></ProtectedRoute>} />
            
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </ConfirmProvider>
      </AuthProvider>
     </CityProvider>
    </BrowserRouter>
   </ErrorBoundary>
  );
}
